on: [push, pull_request_target]
name: Check for vulnerabilities using govulncheck
jobs:
  vulnerability-check:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: 1.21.0
          go-package: "."